version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - web_data:/usr/share/nginx/html

  api:
    image: node:alpine
    command: node -e "require('http').createServer((req,res)=>res.end('OK')).listen(3000)"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  web_data:
